# Generated by Django 2.0.5 on 2018-05-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goToQ8', '0002_auto_20180521_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('children', 'children'), ('shopping', 'shopping'), ('soprts', 'soprts'), ('restaurants', 'restaurants'), ('entertainment', 'entertainment'), ('theaters', 'theaters'), ('cinema', 'cinema'), ('concerts', 'concerts'), ('festivals', 'festivals'), ('trips', 'trips'), ('seminars', 'seminars')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='hot_and_trend',
            field=models.BooleanField(default=False),
        ),
    ]
