# Generated by Django 2.0.5 on 2018-05-25 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goToQ8', '0003_auto_20180525_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='add_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goToQ8.Event'),
        ),
    ]
