# Generated by Django 2.0.5 on 2018-05-26 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goToQ8', '0004_auto_20180525_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('dob', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='plan',
            name='add_event',
        ),
        migrations.AddField(
            model_name='plan',
            name='plans',
            field=models.ManyToManyField(to='goToQ8.Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='publish_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='events',
            field=models.ManyToManyField(to='goToQ8.Event'),
        ),
        migrations.AddField(
            model_name='profile',
            name='plans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goToQ8.Plan'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
