# Generated by Django 2.0.5 on 2018-05-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goToQ8', '0005_auto_20180526_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='title',
        ),
        migrations.AddField(
            model_name='friends',
            name='location',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='friends',
            name='phone_number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='friends',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='events',
            field=models.ManyToManyField(blank=True, to='goToQ8.Event'),
        ),
    ]
