# Generated by Django 2.0.5 on 2018-05-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goToQ8', '0006_auto_20180527_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
