# Generated by Django 2.0.5 on 2018-06-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goToQ8', '0007_auto_20180527_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
